### ISSUE TITLE
Thanks for using our library!

### ISSUE THREAD

**Issue by christopherkindl** [jorgeorejas/factorial-bi#1]
Hi @jorgeorejas, great job on the dashboard! If you would like to share any feedback regarding tremor's developer experience or desired features, feel free to drop me a message :) Happy to hop on a call as well

Cheers, Chris

**Comment by severinlandolt** [comment]
Your dashboard is awesome🚀

**Comment by jorgeorejas** [comment]
Thank you both, @christopherkindl @severinlandolt.

Would be great we could contact and share feedback, you made such an easy to use yet useful and powerful tool, I really struggled before with ChartJS and Tremor was a great discovery through Guillermo Rauch's (Vercel's CEO) twitter.

Greetings, Jorge
